//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreScheduler.Client.Desktop.RemoteService.Scheduler {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteService.Scheduler.ISchedulerExtensionService")]
    public interface ISchedulerExtensionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerExtensionService/RegisterForStream", ReplyAction="http://tempuri.org/ISchedulerExtensionService/RegisterForStreamResponse")]
        void RegisterForStream(string id, string address, int port);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchedulerExtensionService/RegisterForStream", ReplyAction="http://tempuri.org/ISchedulerExtensionService/RegisterForStreamResponse")]
        System.Threading.Tasks.Task RegisterForStreamAsync(string id, string address, int port);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerExtensionServiceChannel : CoreScheduler.Client.Desktop.RemoteService.Scheduler.ISchedulerExtensionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerExtensionServiceClient : System.ServiceModel.ClientBase<CoreScheduler.Client.Desktop.RemoteService.Scheduler.ISchedulerExtensionService>, CoreScheduler.Client.Desktop.RemoteService.Scheduler.ISchedulerExtensionService {
        
        public SchedulerExtensionServiceClient() {
        }
        
        public SchedulerExtensionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerExtensionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerExtensionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerExtensionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RegisterForStream(string id, string address, int port) {
            base.Channel.RegisterForStream(id, address, port);
        }
        
        public System.Threading.Tasks.Task RegisterForStreamAsync(string id, string address, int port) {
            return base.Channel.RegisterForStreamAsync(id, address, port);
        }
    }
}
